cache: pip

matrix:
  include:
    - language: python
      python: "3.6"
      env: TOXENV=py36

    - language: python
      python: "3.6"
      env: TOXENV=pep8

install:
    - pip install tox
    - if [ "$TOXENV" = 'py36' ]; then pip install coveralls; fi
script:
    - tox -e $TOXENV
after_success:
    - if [ "$TOXENV" = 'py36' ]; then coveralls; fi

deploy:
    provider: pypi
    distributions: "sdist bdist_wheel"
    user: seantis
    password:
      secure: "JM0K4gcF/o+uPP17jk7KHUKKpG4/PFGFBqFeXW1Q0ajzmEQ115JVHHxApglcdWZEVaWGv3y+vr+oE/rBhLBZ/hW6oc+5oy7pYxf8L0X31V6QoyB2LDIrCSaWW4pv4ui7Q2dyo7yiCPa0efssGqOlkzVNJNS+LboZLJxYCEYYgv7SFudeUqGaSeh1KrYDx1qoXYkEHbSF+ujx87bBqjXpsjWXK0xfyJ4MLSHwKImt0wICUyVrGSPBUtCyp9z/18QERk6lznQn2UqCHzXfwTAua6nRM+8kgpsFWiE4oBTMTWuLh+7J8UaM4pvwIUcYE6rw5XYBcNTNNNOUktdkrXRGm0RwqTt72SVU/11uXuvE7/VZLOp1Pfbj7+MqR8alR5+7y0sWzxK5HrViiz/5CHCi7MCgtv1frOfqXpC0YeB5XE3bgf7ur+9CEk1r0KgjvxZ8gDqEUTkwWN5JJ29tzWR0o/wSq60ZXLjCatjonkBTwmYV2y+ot5LNwmLG0oJovOJ4odn0WfEtSAHe/4QGnMWSmDCOLoi56u95iVfEFhTz7y+Mxil/Yy3Em3wYcfs4HR9fM79MCDvPAR5avp2qiv5FZP/DIFyXJLHdADdPVQUTChN90uF9wilHXdSy/7hXbuvLFhd3JYUL9LdsHhSbiHRFmVONPKAEIPoRsvfILaikfBA="
    on:
        tags: true
        condition: $TOXENV = py36
